version: '3.8'
services:
  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: db
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      PGUSER: ${DATABASE_USERNAME:-postgres}
      PGDATABASE: db
      PGPASSWORD: ${DATABASE_PASSWORD:-password}
    ports:
      - 127.0.0.1:${DATABASE_LOCAL_PORT:-5435}:5432
    restart: always

  backup:
    build: pg-backup/
    image: 270968290167.dkr.ecr.eu-west-2.amazonaws.com/fmc-db-backup
    restart: always
    volumes:
      - ./backup:/backup
    links:
      - db
    environment:
      SCHEDULE: '@daily'
      POSTGRES_DATABASE: db
      POSTGRES_HOST: db
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_EXTRA_OPTS: '--schema=public --blobs'
      DAYS_HISTORY: 7

  app:
    build: .
    restart: always
    command: bash ./start_server.sh
    # environment:
    # DATABASE_URI: ${PROD_DATABASE_URI}
    ports:
      - 127.0.0.1:${WEB_APP_PORT:-8000}:80
    depends_on:
      - db

volumes:
  db_data:
